// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.BipartiteMatching.CheckBp.checkbp(ChacoSharp.vtx_data**,System.Double*[],System.Int32*,System.Double[],System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.ChacoSequenceJPetit.sequence(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Boolean,System.Double*,ChacoSharp.StaticConstants.LanczosType,System.Boolean,System.Int32,System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.Flow.wbpcover(System.Int32,System.Int32,System.Int32*,System.Int32*,System.Int32*,System.Int32*,System.Int32*,System.Int32**)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.NWayKl.nway_kl(ChacoSharp.vtx_data**,System.Int32,ChacoSharp.bilist****,ChacoSharp.bilist**,System.Int32**,System.Int32**,System.Int32*,System.Int32,System.Int32,System.Double[],System.Single*[],System.Int32[][],System.Int32,System.Boolean,System.Int32**,System.Double[])~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.NWayKl.p1bucket(ChacoSharp.bilist**,ChacoSharp.bilist*,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.NWayKl.pbuckets(ChacoSharp.bilist****,ChacoSharp.bilist**,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.NWayKlv.nway_klv(ChacoSharp.vtx_data**,System.Int32,ChacoSharp.bilist**,ChacoSharp.bilist**,ChacoSharp.bilist*,ChacoSharp.bilist*,System.Int32*,System.Int32*,System.Int32*,System.Int32,System.Double[],System.Int32,System.Int32**,System.Double[])~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Coarsening.NWayKlv.p1bucket(ChacoSharp.bilist**,ChacoSharp.bilist*,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Connect.Connected.print_connected(ChacoSharp.connect_data*)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Connect.ConnectEnforce.connect_enforce(ChacoSharp.vtx_data**,System.Int32,System.Boolean,System.Int32*,System.Double[],System.Int32,System.Int32*,System.Int32*)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Connect.FindComps.bfsearch(ChacoSharp.vtx_data**,System.Int32,System.Int32*,System.Int32*,System.Int32*,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Connect.HeapHelper.heap_extract_max(ChacoSharp.heap*,System.Int32,System.Int32*,System.Int32*)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.Bisect.bisect(System.Double*,System.Double*,System.Int32,System.Double,System.Double*,System.Double*,System.Int32,System.Int32,System.Double,System.Double*,System.Int32)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.GetRitzVals.get_ritzvals(System.Double*,System.Double*,System.Int32,System.Double,System.Double*,System.Double*,System.Int32,System.Int32,System.Int32,System.Double,System.Double)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.LanczosExt.lanczos_ext(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Double*[],System.Double,System.Double*,System.Double,System.Int32,System.Double*,System.Double)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.LanczosExt.lanczos_ext_float(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Double*[],System.Double,System.Double*,System.Double,System.Int32,System.Double*,System.Double)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.LanczosFO.lanczos_FO(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Double*[],System.Double[],System.Double[],System.Double,System.Double*,System.Double,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.LanczosSelectiveOrthogonalization.lanczos_SO(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Double*[],System.Double[],System.Double[],System.Double,System.Double*,System.Double,System.Int32,System.Boolean,System.Int32,System.Int32*,System.Int32*,ChacoSharp.StaticConstants.MappingType,System.Double[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.LanczosSoFloat.lanczos_SO_float(ChacoSharp.vtx_data**,System.Int32,System.Int32,System.Double*[],System.Double[],System.Double[],System.Double,System.Double*,System.Double,System.Int32,System.Boolean,System.Int32,System.Int32*,System.Int32*,ChacoSharp.StaticConstants.MappingType,System.Double[],System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.Rqi.rqi_ext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Eigen.TriSolve.tri_solve(System.Double*,System.Double*,System.Int32,System.Double,System.Double*,System.Double,System.Double*,System.Double*)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ChacoSharp.Input.ReflectInput.reflect_params(ChacoSharp.StaticConstants.PartitioningStrategy,ChacoSharp.StaticConstants.LocalPartitioningStrategy,System.Boolean,System.Int32)")]
